gui:
  theme:
    # Default if no theme
    # selectedLineBgColor:
    #   - reverse

    # https://github.com/folke/tokyonight.nvim/blob/main/extras/lazygit/tokyonight_storm.yml
    activeBorderColor:
      - "#ff9e64"
      - "bold"
    inactiveBorderColor:
      - "#29a4bd"
    searchingActiveBorderColor:
      - "#ff9e64"
      - "bold"
    optionsTextColor:
      - "#7aa2f7"
    selectedLineBgColor:
      - "#2e3c64"
    cherryPickedCommitFgColor:
      - "#7aa2f7"
    cherryPickedCommitBgColor:
      - "#bb9af7"
    markedBaseCommitFgColor:
      - "#7aa2f7"
    markedBaseCommitBgColor:
      - "#e0af68"
    unstagedChangesColor:
      - "#db4b4b"
    defaultFgColor:
      - "#c0caf5"

    # # https://github.com/folke/tokyonight.nvim/blob/main/extras/lazygit/tokyonight_day.yml
    # activeBorderColor:
    #   - "#b15c00"
    #   - "bold"
    # inactiveBorderColor:
    #   - "#4094a3"
    # searchingActiveBorderColor:
    #   - "#b15c00"
    #   - "bold"
    # optionsTextColor:
    #   - "#2e7de9"
    # selectedLineBgColor:
    #   - "#b7c1e3"
    # cherryPickedCommitFgColor:
    #   - "#2e7de9"
    # cherryPickedCommitBgColor:
    #   - "#9854f1"
    # markedBaseCommitFgColor:
    #   - "#2e7de9"
    # markedBaseCommitBgColor:
    #   - "#8c6c3e"
    # unstagedChangesColor:
    #   - "#c64343"
    # defaultFgColor:
    #   - "#3760bf"
