set -g @theme_bg           "#eeeeee"
set -g @theme_fg           "#444444"
set -g @theme_bar_bg       "#d0d0d0"
set -g @theme_accent       "#005faf"
set -g @theme_accent_fg    "#eeeeee"
set -g @theme_border_soft  "#d0d0d0"
